apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfest-dakar-2022
  namespace: staging
spec:
  selector:
    matchLabels:
      app: devfest-teranga
  template:
    metadata:
      labels:
        app: devfest-teranga
    spec:
      containers:
      - name: devfest-dakar-app
        image: papihack/devfest-dakar-demo-app:staging-2002-01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
