apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfest-dakar-2022
  namespace: dev
spec:
  selector:
    matchLabels:
      app: devfest-teranga
  template:
    metadata:
      labels:
        app: devfest-teranga
    spec:
      containers:
      - name: myapp
        image: papihack/devfest-dakar-demo-app:develop-2002-01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            host: devfest-dakar-2022.dev.svc
            port: http
            path: /api/service/healthy
          initialDelaySeconds: 20
          period: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /api/service/ready
        ports:
        - name: http
          containerPort: 8080
