apiVersion: v1
kind: Service
metadata:
  name: devfest-dakar-2022
  namespace: dev
spec:
  type: ClusterIP
  selector:
      app: devfest-teranga
  ports:
  - port: 8080
    name: http
    targetPort: http
