apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devfest-dakar-2022
  namespace: prod
spec:
  rules:
  - host: "devfest-app.prod.localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devfest-dakar-2022
            port:
              name: http
              